#[derive(Debug, Clone, PartialEq)]
pub enum Op {
    Constant(usize),
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Pow,
    Not,
    Negate,
    Equal,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Pop,
    Dup,
    GetGlobal(String),
    SetGlobal(String),
    GetLocal(usize),
    SetLocal(usize),
    GetUpvalue(usize),
    SetUpvalue(usize),
    Closure {
        fn_index: usize,
        upvalues: Vec<(bool, usize)>, // (is_local, index)
    },
    Call(usize),
    GetMethod(String),
    Invoke {
        method_name: String,
        arity: usize,
    },
    JumpIfFalse(usize),
    Jump(usize),
    MakeArray(usize),
    ArrayIndex,
    ArraySet,
    ArrayPush,
    ArrayPop,
    ArraySlice,
    Len, // For Arrays and Strings
    Range,
    StringIndex,
    StringSlice,
    Print,
    Return,
    MakeFacet {
        type_name: String,
        field_count: usize,
    },
    FieldGet(String),
    MakeMap(usize), // pairs
    MapGet,
    MapSet,
    MapDelete,
}
